---
- name: Installing httpd softwares
  hosts: tag_Name_Jenkins
  remote_user: ec2-user
  become: true
  tasks:
    - name: Install httpd package
      yum: name=httpd state=present
    - name: copying index file
      copy: src=index.html dest=/var/www/index.html
    
    - name: Start Service
      service: name=httpd state=started
